version: '3.6'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    # see https://github.com/influxdata/influxdata-docker/issues/543
    # run stat -c '%g' /var/run/docker.sock for gid
    user: telegraf:961
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    env_file:
      - environment.env
    ports:
    - '8125:8125'

  influxdb:
    image: influxdb:2.6-alpine
    container_name: influxdb
    restart: always
    env_file:
      - environment.env
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=user
      - GF_INSTALL_PLUGINS=
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: always
    environment:
      - TZ=Europe/London
    ports:
      - '1880:1880'
    volumes:
      - nodered_data:/data
    user: root:root
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf




volumes:
  mongodb_data: {}
  grafana_data: {}
  influxdb_data: {}
  nodered_data: {}
